### PR TITLE
Add :default case for directory?

### LINKED ISSUE #1: Handle base case of directory?
Hello James, this tiny library here really saved me from the Java purgatory: I was already kind of picturing myself banging my head on the wall while trying to make sense out of Java resources and methods to fetch them when I stumbled across it.

Big thanks.

One thing I have noticed, maybe by design, is that `directory?` does not handle the case where the input url is `nil`, which can happen when chaining directly, for example in this sample (cut for brevity):

```
;; Java resources are the best, how to know if the resource path is a dir?
;; http://stackoverflow.com/questions/20105554/is-there-a-way-to-tell-if-a-classpath-resource-is-a-file-or-a-directory
(->> (str path (when-not (= \/ (last path)) "/")) 
     (.findResource classloader)
     (res/directory? r))
```

Is it something you would like to add by any chance?

### PR DESCRIPTION
**Pull request by arichiardi**
Closes #1

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Could you add a simple test and change `, closes #1` to ` (fixes #1)`? Then I'll merge. :)

**Comment by arichiardi** [comment]
Yes I will address this

**Comment by weavejester** [comment]
You don't need to close the PR - you can just push to the branch the PR is associated with.

**Comment by arichiardi** [comment]
Yes I know but I changed the name of the branch. Anyways, sorry about that ;)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arichiardi** [comment]
If you want to reopen this one,. I will send the fixes here. I just need to send the branch to origin again.

**Pull request closed without merging**
